project:
  type: website
  output-dir: docs
  
website:
  title: "Spencer Paragas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/ParagasSpencer
      - icon: github
        href: https://github.com/skparagas/CS-5805-Blog
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Spencer Paragas"

format:
  html:
    theme: cerulean
    toc: true

editor: source

